notifications:
  email: false
addons:
  apt:
    packages:
    # These packages are required for testing PyQT5 applications on linux
    - x11-utils
    - libxkbcommon-x11-0
matrix:
 include:
 - os: osx
   language: generic
   env:
    - MAC_PYTHON_VERSION=3.6.8
    - MAC_PYTHON_OSX_VERSION=10.6
   sudo: required
 - os: linux
   language: python
   python: 3.8
   services: xvfb
env:
 global:
  # DCOR_API_KEY
  - secure: "XM4d9iG133VWgOlRisJ6Z2APIYeDiojn8Qs6NiniA40VUYLVq0IrFPoRP2LE3RjNlejvL4QJPLk7v1WiOjmcjtxWYupp0qHQDFqn1JPqGb9yW09IqhYybh/n2AdHydmwmUxIfroHQUFdzFUf6dGsWkPVWIAQdUbvuAiyf54AcFWz8cf6arrNsHzh/6y5uro+630b3VMlqTNWrSiUVnfR5+tVo1xB/SBsRZ2RpS83A6CBlGk4dpo0V+yhi8aKzHGBOV0ejZurwWMsqmE5CowS4G4KSsDMQrz1DubAFrjCPI1dj+ePaVmhB+IHLrTESdUc0oQ6SRW7jR5VVt0GMsZqyc/9Ppk9vrlo6/NTt1u4AOoUFs4Wqe5FLYMrvRnDL1w/UCSaC85XBP2Zb6NqyEdWefj9gz6S1TQvCEffZy/t3WxkZjYnaABxFxWnvsYf31gUSMab/vuB+1u1rjnduVZf7NsG8CwDgxkW87uPVs3BjQ4EIptMSgpVoUSAm2O4Apar78q9XPyCyRd6F55ynBI9+Zk7oZEa5RUq7Gp7IKFPl+ZXWyKMasUy5hNL/qaK6HRQ4rVS3qPN0GRAhvbTh0dROv5zWussDMWyMkWUjyxFE1at2iN4GMHqMTJb/Dsoih8WMqpiW9mLwcxHv9csmFFYaUtA58YXOKNOi5x0Bpr6bLU="

install:
# install other dependencies
- source ./.travis/${TRAVIS_OS_NAME}_setup_python.sh $MAC_PYTHON_VERSION $MAC_PYTHON_OSX_VERSION
# install binary packages
- travis_retry pip install --upgrade pip
- travis_retry pip install setuptools wheel
# Linux/macOS tests did not run with PyQt 5.15
- travis_retry pip install threadpoolctl==2.0.0
- travis_retry pip install PyQt5==5.14.2 PyQt5-sip==12.7.2
# install package
- travis_retry pip install -e .
# for tests:
- travis_retry pip install codecov coverage flake8
- pip freeze
script:
- coverage run --source=dcoraid setup.py test
- coverage report -m
- flake8 dcoraid
- flake8 tests
# build
- python setup.py sdist bdist_wheel
- pip install pyinstaller==3.6
- bash ./.travis/${TRAVIS_OS_NAME}_build_app.sh DCOR-Aid $TRAVIS_TAG
after_success:
- codecov
deploy:
  - provider: pypi
    user: "ci_dcor"
    password:
      secure: "uqCTs/uAPYQZULKPzdwmL9RXTRIHKv8RPx1kdN7j7T22S63nu1GEzTo24/EIzINeGVoInDr7SqqKbkOWv7m07uREBzfCOiVtTSicpibhJXUH79/fWGQtbvM4V8vmCzJLa/PeyLrlCvYHYTYsRwKD3WKv4HVDH8od7nUL4Uf6q2Yb/MCS6/Dvo6KGxzGQjcsCvjzxNXZU3k8pvHnzXlHzfFyXYe1jaWS8BKgbDqIJZd47ZmZpTvUV8nBQni7nj4Oqzucz+plI9ZGgWufwfCZ76+njn1El8iI02Iu7k7tGPEppE7xnGQQVNzKZ0V2aYOyHN5OjJk8/4NaCvKHJoiSAlwKJIejybZI0hDZkLq/03EXrRWacJ2YuZD6uur9FMlB1tLptLrPlc450Ks4xKJ5JKVJxd6SmjdMpxP/k09YDZIDqtSUVekNW7Pn/LquljcAClZ+uiMxb90U9NruSpQaF4EizmqXcQh2ijtnBDQUdfBhhgDRf640QGY4b/luw1mYcngF9IQmm0573x2cfEfFva9OhBcHbyz/B3/ZS7x3YeLdKXHBg2IZdvhqwTAGKcgVIKtaUjZYvCQPNnZyglXst9iESbWVEC6SflBam64zcaVFkmfP03Gtis1AQdwcHi9p5bWdH9Zr01Wvz2fPnQim4ayjyVE7XO5OmOTUPS4dLC5s="
    on:
      tags: true
    skip_cleanup: true
    skip_existing: true
  - provider: releases
    api_key:
      secure: "PKoRwHJx9iluiWTzNu8kshzJjkPmSB7InhrfTK/9qLqqgjOWME40e6nwY02OjhWR9OH3tHjJGKqOnFJjIntyFt6JfPym/1456esWaZbOhnoWpvwAfIkB05YTvO8zpJz+wjibvCHbkF2zcUTA7UYzsjsu3S+TdG9jMrE0HzUVubS55sUyLXjfYLpVI++BL2JdRywGbr2hZZlHzlmb7ipz8oS5d1DfwU0cttSbOG93kt0nE0NQBMXor7nEX/Nw3M9+C+S71TNTCIEmFgimKW9YBgn8OBzqB0TOd49u/U6oCAkAw4+QfG6XEhCSRllzQfRLh6n1jqiWtdjy8mVlaDfI+vTzszQhWDwmKIzAVifl2IbyyyvdBoujwzWzwsUtaRQHhlPxAn8CuijD7jFLr5gK14nE2s8/EYz7aPqzRNAiscxPK9Xf3BIfXQvthJiOgchvmVo/x0QAkSKHTCbMI0lFMwKwgXWshsVkXOXGc9y0em2WZpafgBGvRrqKyOcJJJ2+A7EBVWLWBFLANaLYNNW/Pv1eemeoNQA5XkmS2MOXMw/EvwxYafksuq8izmsjqzRCC7fE/Vjxvu0l3UHSOmKSJrW3lwnPIw+qEJr65W3Gwf4jv2oXYm2klB7l97h1oYYrDRQNak7dTYm4KmA9t/GEh7xj25P/lV6QNaSi0bAgzVA="
    file_glob: true
    file:
      - "dist_app/*.dmg"
      - "dist_app/*.pkg"
    skip_cleanup: true
    draft: true
    on:
      tags: true

