# Use large clone depth so that a tag is included for versioning
clone_depth: 256

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
  DCOR_API_KEY:
    secure: fZWCZrKoGp2a/bNqd+quJRsVcRI5Jx774LLx3BX3jDuFAqHEAkGR3M/Wq7IwxXua

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

install:
  # Install InnoSetup and add to path
  - appveyor-retry choco install -y InnoSetup
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  # Check that we have the expected version and architecture for Python
  - python --version
  # Install dcoraid and its dependencies
  - appveyor-retry python -m pip install --upgrade pip
  # Pin version of numpy
  # https://developercommunity.visualstudio.com/content/problem/1207405/fmod-after-an-update-to-windows-2004-is-causing-a.html
  - appveyor-retry pip install "numpy<1.19.4"
  - appveyor-retry pip install -e .
  # Show the installed packages
  - pip freeze

build: off

test_script:
  - python -c "import dcoraid; print(dcoraid.__version__)"
  - pip install coverage
  - pip install codecov
  - coverage run --source=dcoraid ./setup.py test
  - coverage report -m
  # Allow codecov to fail
  - codecov || exit 0

after_test:
  - appveyor-retry pip install twine wheel
  # If tests are successful, create a whl package for the project.
  - python setup.py bdist_wheel
  - python setup.py sdist
  - ps: "ls dist"
  # Install pyinstaller (includes dependency for pywin32)
  - appveyor-retry pip install pyinstaller==4.1
  # Run pyinstaller
  - pyinstaller -y --log-level=WARN build-recipes\win_dcoraid.spec
  # Run the binary (the most simple test)
  - dist\\DCOR-Aid\\DCOR-Aid.exe --version
  # Create InnoSetup installers
  # Generate iss file
  - python build-recipes\\win_make_iss.py
  # Set InnoSetup path here, because Cython complained about it.
  - set PATH=%PATH%;"C:\\Program Files (x86)\\Inno Setup 5"
  - iscc /Q build-recipes\\win_dcoraid.iss

artifacts:
  # InnoSetup files
  - path: build-recipes\Output\*

deploy:
  provider: GitHub
  auth_token:
    secure: /b5SfmYssAfLaWi0qkPhxR5CruSVBZUurSQLEL3RAaRlHn6HTPrkIqvrLDk/8JxB
  artifact: /.*\.exe/
  draft: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only
